name: ci esdk-obs-android

on: [push]

jobs:
  build:

    #runs-on: windows-latest
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: mvn -B package --file pom-android.xml
    - name: Upload artifact
      if: success()
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: esdk-obs-android
        # Destination path
        path: /home/runner/work/huaweicloud-sdk-java-obs/huaweicloud-sdk-java-obs/target/
